import "@/styles/globals.css";
import React from "react";
import type { AppProps } from "next/app";
import Head from "next/head";
import Header from "@/common/Header/Header";


//글로벌 css, 공통 레이아웃 , 테마나 상태관리
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>카페사장님을 위한 일 잘하는 매니저 - 카페매니저</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 공통 헤더 */}
      <Header />
      <Component {...pageProps} />
    </>
  );
}
